config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home
  resources :structure, :only => [:index]
  resources :about, :only => [:index]
  
  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	before_action :logo_color

	def index
		@people = 	{ people: [
								{ name: "Kelly Hong", role: 'President', year: "Senior", major: 'Computer Science' },
								{ name: "Dana Lin", role: 'Internal Vice President', year: "Senior", major: 'Economics' },
								{ name: "Rebecca Zhuge", role: 'External Vice President', year: "Junior", major: 'Political Science' },
								{ name: "Charmaine Lai", role: 'Director of Finance', year: "Junior", major: 'Economics' },
								{ name: "Tiffany Tran", role: 'Director of Operations', year: "Sophomore", major: 'IB & Psychology' },
								{ name: "Justin Zhong", role: 'Senior Advisor', year: "Junior", major: 'Cognitive Science' },
								{ name: "Sarah Zhang", role: 'Senior Advisor', year: "Junior", major: 'MCB' },
								{ name: "Faith Szeto", role: 'Senior Advisor', year: "Senior", major: 'Computer Science' },
								{ name: "Valerie Tan", role: 'Design Chair', year: "Sophomore", major: 'Architecture' },
								{ name: "Everett Kim", role: 'Community Service Chair', year: "Sophomore", major: 'Psychology & Philosophy' },
								{ name: "Brandon Huang", role: 'Development Chair', year: "Junior", major: 'Statistics' },
								{ name: "Emily Zeng", role: 'Historian Chair', year: "Freshmen", major: 'Psychology' },
								{ name: "Peter Ren", role: 'Social Chair', year: "Sophomore", major: 'Chemistry & Computer Science' },
								{ name: "Cloris Zhang", role: 'Public Relations Chair', year: "Sophomore", major: 'Applied Math' },
								{ name: "Jun Zhou", role: 'IRC Chair', year: "Junior", major: 'EECS' },
								{ name: "Jason Louie", role: 'Culture Chair', year: "Sophomore", major: 'Sociology' }
						]
					}.to_json
	end

	def logo_color
		@logo_path = @@aaa_blue
		@color = "#264653"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def logo_path
  	@@aaa_white = ActionController::Base.helpers.asset_url('AAA_offwhite.svg')
  	@@aaa_blue = ActionController::Base.helpers.asset_url('AAA_Blue.svg') 
  	@@aaa_logo = ActionController::Base.helpers.asset_url('AAA_offwhite.svg')
  	@@color = "#FFFFFF"
  	@color = @@color
  end

  before_action :logo_path

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@logo_path = @@aaa_white
	end
end

app/controllers/structure_controller.rb
class StructureController < ApplicationController
	before_action :logo_color

	def index
		# use sample data for nwo
		@data = { 	member: 
						{ 	num: 1, 
							path: 'members', 
							verbose: 'General Members',
							positions: ['General Member'],
							number: 400, 
							link: '/', 
							perks: ["Events", "Family", "Friends", "Facebook Page", "Merchandise"],
							commitment: "Low Commitment",
							dues: "General Member - $15 / Semester",
							description: 'General members make up our largest group in Asian American Association. This is the lowest commitment tier. Come join us as you please!'
						},
					committee: 
						{ 	num:2,
							path: 'committees', 
							verbose: 'Committees',
							positions: ['Committee Member', 'Committee Chair'],
							number: 8, 
							perks: ["Events", "Close knit Family", "Learn new skills"],
							commitment: 'Medium Commitment',
							dues: "General Member - $15 / Semester",
							description: 'Committee members learn a skill throughout the semester and gain a close knite group of friends. This is a higher commitment tier and is a great way to make a difference on campus.',
							links: '/'
						}, 
					family: 
						{ 	num:3, 
							path: 'families', 
							verbose: 'Families',
							positions: ['Family Member', 'Family Head'],
							number: 3,
							perks: ["Events", "Meet new People", "Family Page", "Family Events"], 
							commitment: "Low Commitment",
							description: 'Families are open to all members. As a family member you will have access to Family Events, our big/little system and a large group of people to meet.',
							dues: "General Member - $15 / Semester",
							links: '/'
						}, 
					cabinet: 
						{ 	num: 4, 
							path: 'cabinet', 
							verbose: 'Cabinet Officers',
							positions: ['President', 'External Vice President', 'Internal Vice President', 'Director of Operations', 'Director of Finance', 'Senior Advisor'],
							number: 8, 
							perks: ["Event Planning", "Close knit Family", "Logistics Planning", "Cabinet Gear"],
							commitment: "High Commitment",
							dues: "General Member - $15 / Semester",
							description: 'Cabinet Officers run the behind the scenes work. If you want to help to club grow and gain a deeper understanding of it, join this tier.',
							links: '/'
						}}.to_json
		@active = params[:format]
		if @active.nil?
			@active = :member
		end
	end

	def logo_color
		@logo_path = @@aaa_blue
		@color = "#264653"
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/structure_helper.rb
module StructureHelper
end

app/views/about/index.html.haml
- content_for :head do
	= stylesheet_link_tag 'about'

- content_for :body do
	.center 
		.header-container
			.container.left
				%h1 About
				%p Learn about our Spring 2018 Cabinet!
		#about
		#about-data{people: @people}
		= javascript_pack_tag 'about'

app/views/home/index.html.haml
- content_for :head do
	= stylesheet_link_tag 'home'

- content_for :body do
	.home-container
		.bg.vertical-align
			#bg
				.crane
					= image_tag("Crane.svg", class: "crane-svg")
				.home-desc-container
					.desc
						%h2 The largest Asian American Interest Group on campus
						%p Open to all groups interested in Asian American Culture
				.panel-container
					.panel
						%h2 
							= link_to  'General Members', structure_index_path('member')
					.panel
						%h2 
							= link_to 'Families', structure_index_path('family')
					.panel
						%h2 
							= link_to 'Committes', structure_index_path('committee')
					.panel
						%h2 
							= link_to 'Cabinet', structure_index_path('cabinet')
					.panel
						%h2 Events
					.panel
						%h2 History
				.mobile-container
					%p Click to Learn More!
		.white-bg.vertical-align
			.desc-container
				%h2 Mission
				%h3 Established in 1994, the UC Berkeley Asian American Association is one of the largest cultural clubs and strives to create an environment welcoming to all Asian Americans.
				%p 
			.poly
				= image_tag("Poly_1.svg", class: "poly-1-svg")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ucbaaa
    = csrf_meta_tags
    = stylesheet_link_tag 	 "https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900,900i"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css'
    = yield :head
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #nav_data{data: @logo_path, color: @color, about: about_index_path}
    #nav
    = javascript_pack_tag 'navbar_react'
    = yield :body

app/views/structure/index.html.haml
- content_for :head do
	= stylesheet_link_tag 'structure'

- content_for :body do
	.center 
		.header-container
			.container.left
				%h1 Structure
				%p Find out more about how to get involved!
		#structure-container
		#structure-data{data: @data, active: @active}
		= javascript_pack_tag 'structure_carousel'